FROM python:3.12-alpine


WORKDIR /.

COPY ./requirements.txt .
RUN apk add --no-cache gcc musl-dev libffi-dev \
    && pip install --no-cache-dir --upgrade -r ./requirements.txt \
    && apk del gcc musl-dev libffi-dev

    
COPY ./core /core


COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh


ENTRYPOINT [ "/entrypoint.sh" ]