FROM python:3.12

WORKDIR /.

COPY ./requirements.txt /

COPY ./core /core

RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "core.main:app","--reload" ,"--host", "0.0.0.0", "--port", "8000"]