"""alter Payment table

Revision ID: 565c06a4bcdb
Revises: bbaa11b426d4
Create Date: 2025-10-01 18:13:16.397726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '565c06a4bcdb'
down_revision: Union[str, Sequence[str], None] = 'bbaa11b426d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('description', sa.Text(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'description')
    # ### end Alembic commands ###
